#!/usr/bin/env bash
# vim: set tabstop=4 expandtab autoindent smartindent:
# author: Sylvain Rabot <sylvain@abstraction.fr>
# date: 05/10/2010
# license: lgpl

# -- die function --------------------------------------------------------------

die()
{
    if [ -n "$1" ]; then
        echo >&2 $1;
    fi

    if [ -z "$2" ]; then
        exit 1
    else
        exit $2
    fi
}

# -- usage function ------------------------------------------------------------

usage()
{
    cat <<EOF
Usage: `basename $0` [options] <source> <target>

Options:
  -i            ignore all white space
  -w            ignore case differences in file contents
  -y            Output in two columns
  --no-pager    do not use pager to display output
  -h/--help     show this help
EOF

    exit;
}

# -- tests ---------------------------------------------------------------------

[ `which diff` ]        || die "rdiff needs diff to be installed"
[ `which less` ]        || die "rdiff needs less to be installed"
[ `which tempfile` ]    || die "rdiff needs tempfile to be installed"
[ `which ssh` ]         || die "rdiff needs ssh to be installed"
[ `which grep` ]        || die "rdiff needs grep to be installed"
[ `which getopt` ]      || die "rdiff needs getopt to be installed"

# -- bash completion -----------------------------------------------------------

if [ -f "~/.bash_completion" ]; then
    IS_COMPLETED_ALREADY=$(cat "~/.bash_completion" | grep rdiff)
    
    if [ -z "$IS_COMPLETED_ALREADY" ]; then
        (echo ""; echo "complete -F _ssh rdiff") >> ~/.bash_completion
    fi
elif [ -f "/etc/bash_completion" ]; then
    echo "complete -F _ssh rdiff" >> ~/.bash_completion
fi

# -- default values ------------------------------------------------------------

PAGER=less
DIFF_MODE="-u"

# -- arguments parsing ---------------------------------------------------------

ARGV=`getopt -o w,i,y,h --long no-pager,help -n "$0" -- $0 $@`

if [ $? != 0 ] ; then
    die "Terminating ...";
fi

eval set -- "$ARGV"

while true;
do
    case "$1" in
        -w)             NO_WHITESPACE="-w";         shift;;
        -i)             NO_CASE_CHANGE="-i";        shift;;
        -y)             DIFF_MODE="-y";             shift;;
        --no-pager)     PAGER=cat;                  shift;;
        -h|--help)      usage;;
        --)             shift;                      break;;
        *)              die "Oops ...";;
    esac
done

# ------------------------------------------------------------------------------

SOURCE_INPUT=$2
TARGET_INPUT=$3

IS_SOURCE_INPUT_REMOTE=$(echo "$SOURCE_INPUT" | grep -iE "^[a-z0-9_-@\.]+:.*")
IS_TARGET_INPUT_REMOTE=$(echo "$TARGET_INPUT" | grep -iE "^[a-z0-9_-@\.]+:.*")

if [ -n "$IS_SOURCE_INPUT_REMOTE" ]; then
    SOURCE_INPUT_HOST=$(echo "$SOURCE_INPUT" | cut -d ':' -f1)
    SOURCE_INPUT_PATH=$(echo "$SOURCE_INPUT" | cut -d ':' -f2,3,4,5,6,7,8,9)
elif [ -f $SOURCE_INPUT ]; then
    SOURCE_INPUT_HOST=""
    SOURCE_INPUT_PATH=$SOURCE_INPUT
else
    die "$SOURCE_INPUT neither a local or a remote file"
fi

if [ -n "$IS_TARGET_INPUT_REMOTE" ]; then
    TARGET_INPUT_HOST=$(echo "$TARGET_INPUT" | cut -d ':' -f1)
    TARGET_INPUT_PATH=$(echo "$TARGET_INPUT" | cut -d ':' -f2,3,4,5,6,7,8,9)
elif [ -f $TARGET_INPUT ]; then
    TARGET_INPUT_HOST=""
    TARGET_INPUT_PATH=$TARGET_INPUT
else
    die "$TARGET_INPUT neither a local or a remote file"
fi

# both remote files
if [ -n "$SOURCE_INPUT_HOST" -a -n "$TARGET_INPUT_HOST" ]; then
    SOURCE_INPUT_TEMP=$(tempfile -p rdiff -s "-source")
    TARGET_INPUT_TEMP=$(tempfile -p rdiff -s "-target")
    
    ssh $SOURCE_INPUT_HOST cat $SOURCE_INPUT_PATH > $SOURCE_INPUT_TEMP
    ssh $TARGET_INPUT_HOST cat $TARGET_INPUT_PATH > $TARGET_INPUT_TEMP
    
    diff $DIFF_MODE $NO_WHITESPACE $NO_CASE_CHANGE $SOURCE_INPUT_TEMP $TARGET_INPUT_TEMP | $PAGER
    
    rm $SOURCE_INPUT_TEMP $TARGET_INPUT_TEMP
# only source is a remote file
elif [ -n "$SOURCE_INPUT_HOST" ]; then
    SOURCE_INPUT_TEMP=$(tempfile -p rdiff -s "-source")
    
    ssh $SOURCE_INPUT_HOST cat $SOURCE_INPUT_PATH > $SOURCE_INPUT_TEMP
    
    diff $DIFF_MODE $NO_WHITESPACE $NO_CASE_CHANGE "$SOURCE_INPUT_TEMP" "$TARGET_INPUT_PATH" | $PAGER
    
    rm $SOURCE_INPUT_TEMP
# only target is a remote file
elif [ -n "$TARGET_INPUT_HOST" ]; then
    TARGET_INPUT_TEMP=$(tempfile -p rdiff -s "-target")
    
    ssh $TARGET_INPUT_HOST cat $TARGET_INPUT_PATH > $TARGET_INPUT_TEMP
    
    diff $DIFF_MODE $NO_WHITESPACE $NO_CASE_CHANGE $TARGET_INPUT_TEMP | $PAGER
    
    rm $SOURCE_INPUT_TEMP
else
    diff $DIFF_MODE $NO_WHITESPACE $NO_CASE_CHANGE $SOURCE_INPUT_PATH $TARGET_INPUT_PATH | $PAGER
fi

